export const LOGIN = "LOGIN";

export const FETCH_TOKENS = "FETCH_TOKENS";
export const FETCH_TOKENS_SUCCESS = "FETCH_TOKEN_SUCCESS";
export const FETCH_TOKENS_FAILURE = "FETCH_TOKEN_FAILURE";

export const FETCH_MARKETPLACE_DATA = "FETCH_MARKETPLACE_DATA";
export const FETCH_MARKETPLACE_DATA_SUCCESS = "FETCH_MARKETPLACE_DATA_SUCCESS";
export const FETCH_MARKETPLACE_DATA_FAILURE = "FETCH_MARKETPLACE_DATA_FAILURE";

export const BUY_TOKEN = "BUY_TOKEN";
export const BUY_TOKEN_SUCCESS = "BUY_TOKEN_SUCCESS";
export const BUY_TOKEN_FAILURE = "BUY_TOKEN_FAILURE";

export const FETCH_USER_NFT = "FETCH_USER_NFT";
export const FETCH_USER_NFT_SUCCESS = "FETCH_USER_NFT_SUCCESS";
export const FETCH_USER_NFT_FAILURE = "FETCH_USER_NFT_FAILURE";

export const ADD_TO_NEWSLETTER = "ADD_TO_NEWSLETTER";
export const ADD_TO_NEWSLETTER_SUCCESS = "ADD_TO_NEWSLETTER_SUCCESS";
export const ADD_TO_NEWSLETTER_FAILURE = "ADD_TO_NEWSLETTER_FAILURE";

// export const
