export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_USERNAME_SUCCESS = "UPDATE_USERNAME_SUCCESS";
export const UPDATE_USERNAME_FAILURE = "UPDATE_USERNAME_FAILURE";

export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS";
export const UPDATE_EMAIL_FAILURE = "UPDATE_EMAIL_FAILURE";

export const UPDATE_PHONE = "UPDATE_PHONE";
export const UPDATE_PHONE_SUCCESS = "UPDATE_PHONE_SUCCESS";
export const UPDATE_PHONE_FAILURE = "UPDATE_PHONE_FAILURE";

export const UPDATE_SOCIAL_ACCOUNTS = "UPDTE_SOCIAL_ACCOUNTS";
export const UPDATE_SOCIAL_ACCOUNTS_SUCCESS = "UPDTE_SOCIAL_ACCOUNTS_SUCCESS";
export const UPDATE_SOCIAL_ACCOUNTS_FAILURE = "UPDTE_SOCIAL_ACCOUNTS_FAILURE";

export const UPDATE_NOTIFICATION_SETTINGS = "UPDATE_NOTIFICATION_SETTINGS";
export const UPDATE_NOTIFICATION_SETTINGS_SUCCESS =
  "UPDATE_NOTIFICATION_SUCCESS";
export const UPDATE_NOTIFICATION_SETTINGS_FAILURE =
  "UPDATE_NOTIFICATION_FAILURE";

export const DELETE_ACCOUNT_PERMANENTLY = "DELETE_ACCOUNT_PERMANENTLY";
export const DELETE_ACCOUNT_PERMANENTLY_SUCCESS =
  "DELETE_ACCOUNT_PERMANENTLY_SUCCESS";
export const DELETE_ACCOUNT_PERMANENTLY_FAILURE =
  "DELETE_ACCOUNT_PERMANENTLY_FAILURE";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const LOGIN_BY_LOCAL_STORAGE = "LOGIN_BY_LOCAL_STORAGE";
export const LOGIN_BY_LOCAL_STORAGE_SUCCESS = "LOGIN_BY_LOCAL_STORAGE_SUCCESS";
export const LOGIN_BY_LOCAL_STORAGE_FAILURE = "LOGIN_BY_LOCAL_STORAGE_FAILURE";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE";

export const CREATE_PKH_PK = "CREATE_PKH_PK";
export const CREATE_PKH_PK_SUCCESS = "CREATE_PKH_PK_SUCCESS";
export const CREATE_PKH_PK_FAILURE = "CREATE_PKH_PK_FAILURE";

export const CHECK_CREATE_SUCCESS = "CHECK_CREATE_SUCCESS";
export const CHECK_CREATE_SUCCESS_SUCCESS = "CHECK_CREATE_SUCCESS_SUCCESS";
export const CHECK_CREATE_SUCCESS_FAILURE = "CHECK_CREATE_SUCCESS_FAILURE";

export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const VERIFY_FORGOT_TOKEN = "VERIFY_FORGOT_TOKEN";
export const VERIFY_FORGOT_TOKEN_SUCCESS = "VERIFY_FORGOT_TOKEN_FAILURE";
export const VERIFY_FORGOT_TOKEN_FAILURE = "VERIFY_FORGOT_TOKEN_FAILURE";

export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS";
export const UPDATE_USER_PASSWORD_FAILURE = "UPDATE_USER_PASSWORD_FAILURE";

// export const
